/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package janelas;

import exerc1.Inteiro;
import javax.swing.JOptionPane;

/**
 *
 * @author Joao Filipe
 */
public class JanelaInteiro extends javax.swing.JFrame {
    Inteiro obj = new Inteiro();
    /**
     * Creates new form JanelaInteiro
     */
    public JanelaInteiro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle1 = new javax.swing.JLabel();
        jTextFieldNum1 = new javax.swing.JTextField();
        jLabelTitle2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNum2 = new javax.swing.JTextField();
        jButtonSum = new javax.swing.JButton();
        jButtonSub = new javax.swing.JButton();
        jButtonTimes = new javax.swing.JButton();
        jButtonDiv = new javax.swing.JButton();
        jButtonAbs = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitle1.setFont(new java.awt.Font("DialogInput", 0, 11)); // NOI18N
        jLabelTitle1.setText("CALCULADORA");

        jLabelTitle2.setFont(new java.awt.Font("DialogInput", 0, 11)); // NOI18N
        jLabelTitle2.setText("Numero 01: ");

        jLabel1.setFont(new java.awt.Font("DialogInput", 0, 11)); // NOI18N
        jLabel1.setText("Numero 02:");

        jButtonSum.setText("ADICAO");
        jButtonSum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSumMouseClicked(evt);
            }
        });
        jButtonSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSumActionPerformed(evt);
            }
        });

        jButtonSub.setText("SUBTRACAO");
        jButtonSub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSubMouseClicked(evt);
            }
        });

        jButtonTimes.setText("MULTIPLICACAO");
        jButtonTimes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonTimesMouseClicked(evt);
            }
        });

        jButtonDiv.setText("DIVISAO");
        jButtonDiv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDivMouseClicked(evt);
            }
        });

        jButtonAbs.setText("ABSOLUTO");
        jButtonAbs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAbsMouseClicked(evt);
            }
        });

        jLabel2.setText("(Para o valor absoluto digitar apenas no Numero 01)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitle2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldNum1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jTextFieldNum2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jButtonSum)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSub)
                        .addGap(0, 41, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAbs)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonTimes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonDiv)))
                        .addGap(30, 30, 30))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLabelTitle1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel2)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabelTitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTitle2))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSum)
                            .addComponent(jButtonSub))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonDiv)
                            .addComponent(jButtonTimes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAbs)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(514, 260));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSumActionPerformed

    private void jButtonSumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSumMouseClicked
        // TODO add your handling code here:
        String s1 = jTextFieldNum1.getText(), s2 = jTextFieldNum2.getText();
        int n1 = Integer.parseInt(s1), n2 = Integer.parseInt(s2), resultado;
        obj.carregaValor(n1);
        resultado = obj.soma(n2);
        JOptionPane.showMessageDialog(this,
                    resultado, "RESULTADO DA SOMA",
                    JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonSumMouseClicked

    private void jButtonSubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSubMouseClicked
        // TODO add your handling code here:
        String s1 = jTextFieldNum1.getText(), s2 = jTextFieldNum2.getText();
        int n1 = Integer.parseInt(s1), n2 = Integer.parseInt(s2), resultado;
        obj.carregaValor(n1);
        resultado = obj.subtrai(n2);
        JOptionPane.showMessageDialog(this,
                    resultado, "RESULTADO DA SUBTRACAO",
                    JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonSubMouseClicked

    private void jButtonTimesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTimesMouseClicked
        // TODO add your handling code here:
        String s1 = jTextFieldNum1.getText(), s2 = jTextFieldNum2.getText();
        int n1 = Integer.parseInt(s1), n2 = Integer.parseInt(s2), resultado;
        obj.carregaValor(n1);
        resultado = obj.multiplicaPor(n2);
        JOptionPane.showMessageDialog(this,
                    resultado, "RESULTADO DA MULTIPLICACAO",
                    JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonTimesMouseClicked

    private void jButtonDivMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDivMouseClicked
        // TODO add your handling code here:
        String s1 = jTextFieldNum1.getText(), s2 = jTextFieldNum2.getText();
        int n1 = Integer.parseInt(s1), n2 = Integer.parseInt(s2);
        double resultado;
        obj.carregaValor(n1);
        resultado = obj.dividePor(n2);
        JOptionPane.showMessageDialog(this,
                    resultado, "RESULTADO DA DIVISAO",
                    JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonDivMouseClicked

    private void jButtonAbsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAbsMouseClicked
        // TODO add your handling code here:
        String s1 = jTextFieldNum1.getText();
        int n1 = Integer.parseInt(s1), resultado;
        obj.carregaValor(n1);
        resultado = obj.devolveValorAbsoluto();
        JOptionPane.showMessageDialog(this,
                    resultado, "RESULTADO VALOR ABSOLUTO",
                    JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonAbsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaInteiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaInteiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaInteiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaInteiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaInteiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbs;
    private javax.swing.JButton jButtonDiv;
    private javax.swing.JButton jButtonSub;
    private javax.swing.JButton jButtonSum;
    private javax.swing.JButton jButtonTimes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelTitle1;
    private javax.swing.JLabel jLabelTitle2;
    private javax.swing.JTextField jTextFieldNum1;
    private javax.swing.JTextField jTextFieldNum2;
    // End of variables declaration//GEN-END:variables
}
